env:  
  node: true 
  es6: true 
extends:  
  - plugin:@typescript-eslint/recommended  
  - prettier/@typescript-eslint  
  - plugin:prettier/recommended  
parser: '@typescript-eslint/parser'  
parserOptions:  
  ecmaVersion: latest
  project: ./tsconfig.json  
plugins:  
 - '@typescript-eslint'
    